### New *pop files, th = 2.1, second time with new *pop file, new *pop files from january 2025

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
import getdata
import sortdata
import plotting 
import numpy as np
from tabulate import tabulate
import unique_objects
from main_frag_and_rest import main_magnitude_cut
from getdata import PopulationType, data_for_one_year_one_seed, data_returner


base_dir = os.path.join("output", "results_simulations_magnitude_cut_newpop_jan")
os.makedirs(base_dir, exist_ok=True)
getdata.clear_directory(base_dir)

#year ranges, the data of one range ends up in one plot
year_ranges = [np.arange(2002, 2006), np.arange(2006, 2010), np.arange(2010, 2014), np.arange(2014, 2018), np.arange(2019, 2024)]
seeds = [1]

# Variables to store the number of objects in each range for each orbit type
num_0205_GEO, num_0205_GTO, num_0205_fol = 0, 0, 0
num_0609_GEO, num_0609_GTO, num_0609_fol = 0, 0, 0
num_1013_GEO, num_1013_GTO, num_1013_fol = 0, 0, 0
num_1417_GEO, num_1417_GTO, num_1417_fol = 0, 0, 0
num_1923_GEO, num_1923_GTO, num_1923_fol = 0, 0, 0

for years in year_ranges: 
    crs_all_seeds = []
    det_all_seeds = []
    
    # Process data for each year and seed
    for seed in seeds: 
        crs_data_single_years = []
        det_data_single_years = []

        for year in years: 
            population_type = PopulationType.NEWPOP_JAN
            data_crs, data_det = data_for_one_year_one_seed(str(year), seed, population_type)
            crs_data_single_years.append(data_crs)
            det_data_single_years.append(data_det)

        # Convert lists to arrays before hstack
        crs_data_single_years = np.hstack(crs_data_single_years)
        det_data_single_years = np.hstack(det_data_single_years)

        # Append to lists for each seed
        crs_all_seeds.append(crs_data_single_years)
        det_all_seeds.append(det_data_single_years)

    # Clear and create directory for each four-year range
    four_years_dir = os.path.join(base_dir, f"results_{years[0]}_{years[-1]}")
    os.makedirs(four_years_dir, exist_ok=True)
    getdata.clear_directory(four_years_dir)
    
    # Call the function for four-year data
    num_GEO, num_GTO, num_fol = getdata.data_four_years_one_seed(crs_all_seeds, det_all_seeds, years, four_years_dir, f"", seeds, population_type = PopulationType.NEWPOP_JAN)

    # Print the unique/total ratio for the four-year period
    combined_data_det = np.hstack(det_all_seeds)
    combined_data_det = np.array(combined_data_det)
    TLE, frag, rest = sortdata.data_sorter(combined_data_det, 8, 10, 9, 20, 3)
    if frag.size > 0 and rest.size > 0:
        combined_data_det = np.vstack([frag, rest])
    elif frag.size > 0:
        combined_data_det = frag
    elif rest.size > 0:
        combined_data_det = rest
    else:
        print("Both arrays are empty. No data to combine.")
        combined_data_det = np.array([])     
    print(combined_data_det.shape)

    # Store the results in the corresponding variables based on the year range
    if years[0] == 2002:
        num_0205_GEO, num_0205_GTO, num_0205_fol = num_GEO, num_GTO, num_fol
    elif years[0] == 2006:
        num_0609_GEO, num_0609_GTO, num_0609_fol = num_GEO, num_GTO, num_fol
    elif years[0] == 2010:
        num_1013_GEO, num_1013_GTO, num_1013_fol = num_GEO, num_GTO, num_fol
    elif years[0] == 2014:
        num_1417_GEO, num_1417_GTO, num_1417_fol = num_GEO, num_GTO, num_fol
    elif years[0] == 2019:
        num_1923_GEO, num_1923_GTO, num_1923_fol = num_GEO, num_GTO, num_fol


[2002 2003 2004 2005]
Shape of crs_all_seeds[0]: (25, 64892)
Shape of det_all_seeds[0]: (25, 14261)
The ratio of detected objects vs. crossing objects: 0.227
The ratio of detected objects vs. crossing objects: 0.227
The corrected ratio of detected objects vs. crossing objects: 0.227
(25, 5354)
[2006 2007 2008 2009]
Shape of crs_all_seeds[0]: (25, 68670)
Shape of det_all_seeds[0]: (25, 12496)
The ratio of detected objects vs. crossing objects: 0.223
The ratio of detected objects vs. crossing objects: 0.223
The corrected ratio of detected objects vs. crossing objects: 0.223
(25, 5253)
[2010 2011 2012 2013]
Shape of crs_all_seeds[0]: (25, 18902)
Shape of det_all_seeds[0]: (25, 3479)
The ratio of detected objects vs. crossing objects: 0.242
The ratio of detected objects vs. crossing objects: 0.242
The corrected ratio of detected objects vs. crossing objects: 0.242
(25, 1291)
[2014 2015 2016 2017]
Shape of crs_all_seeds[0]: (25, 24265)
Shape of det_all_seeds[0]: (25, 3911)
The ratio of dete

ValueError: zero-size array to reduction operation minimum which has no identity

<Figure size 640x480 with 0 Axes>

## New *.pop files, threshold factor = 2.1

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import os
import getdata
import sortdata
import plotting 
import numpy as np
from tabulate import tabulate
import unique_objects
from main_frag_and_rest import main_magnitude_cut

# Define directories
base_dir = os.path.join("output", "results_simulations_magnitude_cut_newpop")
os.makedirs(base_dir, exist_ok=True)
getdata.clear_directory(base_dir)

#year ranges, the data of one range ends up in one plot
year_ranges = [np.arange(2019, 2024)] #[np.arange(2014, 2018), np.arange(2019, 2024)] #because there are no observations in 2018, we do not plot the simulations for 2018 to make things comparable
seeds = [1, 2, 3, 4]

# Variables to store the number of objects in each range for each orbit type
#num_1418_GEO, num_1418_GTO, num_1418_fol = 0, 0, 0
#num_1923_GEO, num_1923_GTO, num_1923_fol = 0, 0, 0

#tolerances = [0, 0.1, np.Inf, 0, np.Inf, np.Inf, np.Inf, np.Inf, 0.001, 0.1, 0.001, 0.1, 0.1, 1, 1, 1, np.Inf, 0.1, np.Inf, np.Inf, 1, 1, np.Inf, np.Inf, np.Inf]

for years in year_ranges: 
    crs_all_seeds = []
    det_all_seeds = []
    
    # Process data for each year and seed
    for seed in seeds: 
        crs_data_single_years = []
        det_data_single_years = []

        for year in years: 
            data_crs, data_det = getdata.data_for_one_year_one_seed_newpop(str(year), seed)
            crs_data_single_years.append(data_crs)
            det_data_single_years.append(data_det)

        # Convert lists to arrays before hstack
        crs_data_single_years = np.hstack(crs_data_single_years)
        det_data_single_years = np.hstack(det_data_single_years)

        # Append to lists for each seed
        crs_all_seeds.append(crs_data_single_years)
        det_all_seeds.append(det_data_single_years)

    # Clear and create directory for each four-year range
    four_years_dir = os.path.join(base_dir, f"results_{years[0]}_{years[-1]}")
    os.makedirs(four_years_dir, exist_ok=True)
    getdata.clear_directory(four_years_dir)
    
    # Call the function for four-year data
    num_GEO, num_GTO, num_fol = getdata.data_four_years_one_seed(crs_all_seeds, det_all_seeds, years, four_years_dir, f" threshold: 2.1",  seeds)



[2019 2020 2021 2022 2023]
The ratio of detected objects vs. crossing objects: 0.227
The ratio of detected objects vs. crossing objects: 0.227
The corrected ratio of detected objects vs. crossing objects: 0.227
The ratio of detected objects vs. crossing objects: 0.228
The ratio of detected objects vs. crossing objects: 0.228
The corrected ratio of detected objects vs. crossing objects: 0.228
The ratio of detected objects vs. crossing objects: 0.229
The ratio of detected objects vs. crossing objects: 0.229
The corrected ratio of detected objects vs. crossing objects: 0.229
The ratio of detected objects vs. crossing objects: 0.230
The ratio of detected objects vs. crossing objects: 0.230
The corrected ratio of detected objects vs. crossing objects: 0.230


<Figure size 640x480 with 0 Axes>

## New *.pop files, threshold factor = 3.0

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
import getdata
import sortdata
import plotting 
import numpy as np
from tabulate import tabulate
import unique_objects
from main_frag_and_rest import main_magnitude_cut
from getdata import PopulationType, data_for_one_year_one_seed, data_returner

# Define directories
base_dir = os.path.join("output", "results_simulations_magnitude_cut_newpop_th3")
os.makedirs(base_dir, exist_ok=True)
getdata.clear_directory(base_dir)

#year ranges, the data of one range ends up in one plot
year_ranges = [np.arange(2019, 2024)] #[np.arange(2014, 2018), np.arange(2019, 2024)] #because there are no observations in 2018, we do not plot the simulations for 2018 to make things comparable
seeds = [1, 2, 3, 4]

# Variables to store the number of objects in each range for each orbit type
#num_1418_GEO, num_1418_GTO, num_1418_fol = 0, 0, 0
#num_1923_GEO, num_1923_GTO, num_1923_fol = 0, 0, 0

#tolerances = [0, 0.1, np.Inf, 0, np.Inf, np.Inf, np.Inf, np.Inf, 0.001, 0.1, 0.001, 0.1, 0.1, 1, 1, 1, np.Inf, 0.1, np.Inf, np.Inf, 1, 1, np.Inf, np.Inf, np.Inf]

for years in year_ranges: 
    crs_all_seeds = []
    det_all_seeds = []
    
    # Process data for each year and seed
    for seed in seeds: 
        crs_data_single_years = []
        det_data_single_years = []

        for year in years: 
            data_crs, data_det = getdata.data_for_one_year_one_seed_newpop_th3(str(year), seed)
            crs_data_single_years.append(data_crs)
            det_data_single_years.append(data_det)

        # Convert lists to arrays before hstack
        crs_data_single_years = np.hstack(crs_data_single_years)
        det_data_single_years = np.hstack(det_data_single_years)

        # Append to lists for each seed
        crs_all_seeds.append(crs_data_single_years)
        det_all_seeds.append(det_data_single_years)

    # Clear and create directory for each four-year range
    four_years_dir = os.path.join(base_dir, f"results_{years[0]}_{years[-1]}")
    os.makedirs(four_years_dir, exist_ok=True)
    getdata.clear_directory(four_years_dir)
    
    # Call the function for four-year data
    num_GEO, num_GTO, num_fol = getdata.data_four_years_one_seed(crs_all_seeds, det_all_seeds, years, four_years_dir, f" threshold: 3.0",  seeds)


NameError: name 'PopulationType' is not defined